#include "get_next_line.h"

#include "src/ft_strdup.c"
#include "src/ft_substr.c"
#include "src/ft_strjoin.c"
#include "src/ft_strchr.c"
#include "src/ft_putstr.c"
#include "src/ft_putnbr.c"
#include "src/ft_strlen.c"
#include "src/ft_lstfind.c"
#include "src/ft_lstadd_front.c"
#include "src/ft_lstnew.c"
#include "src/ft_memcmp.c"
#include "src/ft_bzero.c"
#include "src/ft_lstdel.c"
#include "src/ft_lstsize.c"
